page_block:
_array_structures:
  page_blocks:
    - label: Banner
      icon: article
      value: 
        _id: banner
        title: Banner
        bg-img: 
        banner-text: This is a subtitle
    - label: gallery
      icon: article
      value: 
        _id: gallery
        gallery-column-count: 4
        gallery:
          - image: https://picsum.photos/100/300
            column-width: 1
            aspect-ratio: landscape
            


